cloud:
  aws:
    credentials:
      access-key: AKIAIO6MU37NXXRXLCFA
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false


application:
  bucket:
    name: bittrix


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8989